name: build-github-actions
run-name: ${{ github.actor }} is launch build procedure 
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mvn clean verify
      